const EVENTS = Object.freeze({
  // Candidate events
  CANDIDATE_REGISTERED: "candidate.registered",
  CANDIDATE_EMAIL_VERIFICATION_OTP: "candidate.email_verification_otp",
  CANDIDATE_LOGIN_OTP: "candidate.login_otp",
  CANDIDATE_PASSWORD_RESET_REQUESTED: "candidate.password_reset_requested",
  CANDIDATE_PASSWORD_CHANGED: "candidate.password_changed",
  CANDIDATE_APPLICATION_SUBMITTED: "candidate.application_submitted",
  CANDIDATE_APPLICATION_SHORTLISTED: "candidate.application_shortlisted",
  CANDIDATE_APPLICATION_REJECTED: "candidate.application_rejected",
  CANDIDATE_INTERVIEW_SCHEDULED: "candidate.interview_scheduled",
  CANDIDATE_INTERVIEW_RESCHEDULED: "candidate.interview_rescheduled",
  CANDIDATE_OFFER_ISSUED: "candidate.offer_issued",
  CANDIDATE_OFFER_ACCEPTED: "candidate.offer_accepted",

  // Recruiter events
  RECRUITER_REGISTERED: "recruiter.registered",
  RECRUITER_PASSWORD_RESET_REQUESTED: "recruiter.password_reset_requested",
  RECRUITER_JOB_POSTED: "recruiter.job_posted",
  RECRUITER_NEW_APPLICATION_RECEIVED: "recruiter.new_application_received",
  RECRUITER_OFFER_RESPONSE: "recruiter.offer_response",
  RECRUITER_INTERVIEW_CONFIRMATION: "recruiter.interview_confirmation",

  // Admin events
  ADMIN_NEW_RECRUITER_REGISTRATION: "admin.new_recruiter_registration",
  ADMIN_HIGH_EMAIL_FAILURE_RATE: "admin.high_email_failure_rate",
  ADMIN_DAILY_SUMMARY: "admin.daily_summary",
  ADMIN_PRODUCTION_ALERT: "admin.production_alert",

  // Recommendation events
  PRO_RECOMMENDATIONS_GENERATED: "pro.recommendations.generated",
  ELITE_RECOMMENDATIONS_GENERATED: "elite.recommendations.generated",
});

const EVENT_CATEGORIES = Object.freeze({
  APPLICATION_UPDATES: "applicationUpdates",
  MARKETING_EMAILS: "marketingEmails",
  JOB_RECOMMENDATIONS: "jobRecommendations",
  BLOG_UPDATES: "blogUpdates",
});

const EVENT_PREFERENCES_MAP = Object.freeze({
  [EVENTS.CANDIDATE_APPLICATION_SHORTLISTED]: EVENT_CATEGORIES.APPLICATION_UPDATES,
  [EVENTS.CANDIDATE_APPLICATION_REJECTED]: EVENT_CATEGORIES.APPLICATION_UPDATES,
  [EVENTS.CANDIDATE_OFFER_ISSUED]: EVENT_CATEGORIES.APPLICATION_UPDATES,
  [EVENTS.CANDIDATE_INTERVIEW_SCHEDULED]: EVENT_CATEGORIES.APPLICATION_UPDATES,
  [EVENTS.CANDIDATE_INTERVIEW_RESCHEDULED]: EVENT_CATEGORIES.APPLICATION_UPDATES,
  [EVENTS.RECRUITER_NEW_APPLICATION_RECEIVED]: EVENT_CATEGORIES.APPLICATION_UPDATES,
  [EVENTS.RECRUITER_JOB_POSTED]: EVENT_CATEGORIES.JOB_RECOMMENDATIONS,
  [EVENTS.PRO_RECOMMENDATIONS_GENERATED]: EVENT_CATEGORIES.JOB_RECOMMENDATIONS,
  [EVENTS.ELITE_RECOMMENDATIONS_GENERATED]: EVENT_CATEGORIES.JOB_RECOMMENDATIONS,
});

const ALWAYS_SEND_EVENTS = Object.freeze([
  EVENTS.CANDIDATE_REGISTERED,
  EVENTS.CANDIDATE_EMAIL_VERIFICATION_OTP,
  EVENTS.CANDIDATE_LOGIN_OTP,
  EVENTS.CANDIDATE_PASSWORD_RESET_REQUESTED,
  EVENTS.CANDIDATE_PASSWORD_CHANGED,
  EVENTS.CANDIDATE_OFFER_ACCEPTED,
  EVENTS.RECRUITER_REGISTERED,
  EVENTS.RECRUITER_PASSWORD_RESET_REQUESTED,
  EVENTS.ADMIN_NEW_RECRUITER_REGISTRATION,
  EVENTS.ADMIN_HIGH_EMAIL_FAILURE_RATE,
  EVENTS.ADMIN_DAILY_SUMMARY,
  EVENTS.ADMIN_PRODUCTION_ALERT,
]);

const SKIP_PREFERENCES_EVENTS = Object.freeze([
  ...ALWAYS_SEND_EVENTS,
]);

module.exports = {
  EVENTS,
  EVENT_CATEGORIES,
  EVENT_PREFERENCES_MAP,
  ALWAYS_SEND_EVENTS,
  SKIP_PREFERENCES_EVENTS,
};
