const mongoose = require("mongoose");

const resdexSearchSchema = new mongoose.Schema({
  companyId: { type: mongoose.Schema.Types.ObjectId, ref: "Company", required: true, index: true },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
  name: { type: String, default: "" },
  isPinned: { type: Boolean, default: false },
  isScheduled: { type: Boolean, default: false },
  scheduleCron: { type: String, default: "" },
  filters: {
    keyword: { type: String, default: "" },
    skills: [String],
    booleanQuery: { type: String, default: "" },
    currentCompany: { type: String, default: "" },
    previousCompany: { type: String, default: "" },
    designation: { type: String, default: "" },
    excludeKeywords: { type: String, default: "" },
    preferredSkills: [String],
    minExperience: { type: Number, default: 0 },
    maxExperience: { type: Number, default: 30 },
    currentCity: [String],
    preferredCity: [String],
    remote: { type: Boolean, default: false },
    hybrid: { type: Boolean, default: false },
    relocation: { type: Boolean, default: false },
    currency: { type: String, default: "INR" },
    currentSalaryMin: { type: Number, default: 0 },
    currentSalaryMax: { type: Number, default: 0 },
    expectedSalaryMin: { type: Number, default: 0 },
    expectedSalaryMax: { type: Number, default: 0 },
    noticePeriod: [String],
    department: { type: String, default: "" },
    role: { type: String, default: "" },
    industry: { type: String, default: "" },
    employmentType: { type: String, default: "" },
    employmentStatus: { type: String, default: "" },
    ug: { type: String, default: "" },
    pg: { type: String, default: "" },
    doctorate: { type: String, default: "" },
    institute: { type: String, default: "" },
    university: { type: String, default: "" },
    graduationYear: { type: String, default: "" },
    minPercentage: { type: Number, default: 0 },
    certifications: [String],
    diversityGender: [String],
    careerBreak: { type: Boolean, default: false },
    veterans: { type: Boolean, default: false },
    disabilities: { type: Boolean, default: false },
    returnship: { type: Boolean, default: false },
    womenHiring: { type: Boolean, default: false },
    campusHiring: { type: Boolean, default: false },
    freshers: { type: Boolean, default: false },
    minAge: { type: Number, default: 0 },
    maxAge: { type: Number, default: 0 },
    languages: [String],
    workPermit: [String],
    passport: { type: Boolean, default: false },
    visa: { type: String, default: "" },
    openToRemote: { type: Boolean, default: false },
    portfolio: { type: String, default: "" },
    github: { type: String, default: "" },
    linkedIn: { type: String, default: "" },
  },
  resultCount: { type: Number, default: 0 },
  runCount: { type: Number, default: 1 },
  lastRunAt: { type: Date, default: null },
  sharedWith: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
}, { timestamps: true });

resdexSearchSchema.index({ companyId: 1, isPinned: -1, updatedAt: -1 });
resdexSearchSchema.index({ userId: 1, updatedAt: -1 });
resdexSearchSchema.index({ companyId: 1, name: 1, lastRunAt: -1 });

module.exports = mongoose.model("ResdexSearch", resdexSearchSchema);
